export const actionTypes = {
  email: 'em',
  ensure: 'en',
  fieldType: 'ft',
  greaterThan: 'gt',
  integer: 'int',
  length: 'lg',
  lessThan: 'lt',
  lowercase: 'lc',
  matches: 'mt',
  max: 'mx',
  min: 'mn',
  negative: 'ng',
  of: 'of',
  positive: 'ps',
  ref: 'rf',
  required: 'rq',
  round: 'rd',
  trim: 'tm',
  truncate: 'tr',
  uppercase: 'uc',
};

export const validActions = {
  Array: [
    actionTypes.ensure,
    actionTypes.length,
    actionTypes.max,
    actionTypes.min,
    actionTypes.required,
  ],
  Boolean: [actionTypes.required],
  Date: [actionTypes.max, actionTypes.min, actionTypes.required],
  Number: [
    actionTypes.greaterThan,
    actionTypes.integer,
    actionTypes.lessThan,
    actionTypes.max,
    actionTypes.min,
    actionTypes.negative,
    actionTypes.positive,
    actionTypes.ref,
    actionTypes.required,
    actionTypes.round,
    actionTypes.truncate,
  ],
  Object: [actionTypes.required],
  String: [actionTypes.length, actionTypes.required],
};

export const getActionType = type => actionTypes[type];
